### Login
POST http://localhost:3000/api/v1/platform/login
Content-Type: application/json

{
  "email": "federico@example.com",
  "password": "adminadmin"
}

###

### Register
POST http://localhost:3000/api/v1/platform/users
Content-Type: application/json

{
  "email": "federico@example.com",
  "password": "adminadmin"
}

###